### ISSUE TITLE
MacOSでMoralerspaceNF_v0.0.4の検証エラー

### ISSUE THREAD

**Issue by skpersonal** [yuru7/moralerspace#2]
postテーブルの使用性でエラーが出てしまいます。
もしかしたらこの件と原因が同じかもしれません。
https://github.com/yuru7/HackGen/issues/12

**Comment by yuru7** [comment]
ご報告ありがとうございます。
おそらく同じ原因と思われますね…。

相変わらず私がMac未所持なもので検証できないので、解消に向けてご協力を賜われると幸いです。

まず状況としては、

- v0.0.2 まではインストールできる
- v0.0.3 からはインストールできない

という状況で合ってますか？

**Comment by yuru7** [comment]
すみません、そもそもNerd Fonts版でのみ発生するということでしたかね？ (HackGenのときのエラー報告もよくよく読んでいくと、Nerd Fonts版のみの事象でした)

**Comment by skpersonal** [comment]
- Nerd Fonts版でのみ発生します。通常版及びJPDOC版、HF版は検証できました。
- v0.0.3以前はNerd Fonts版が存在しないため不明です。

**Comment by yuru7** [comment]
情報ありがとうございます。
Nerd Fonts版のみで発生するということなので、問題はNerd Fontsのpostテーブルの持ち方にありそう、というところで当たりを付け修正してみました。
ビルドしたフォントファイルを以下にアップしておきましたので、これで解消されるか試してみていただいてもいいでしょうか？
https://github.com/yuru7/moralerspace/tree/issue2/test_build

**Comment by skpersonal** [comment]
問題が解消されたことを確認しました。
お忙しい中修正ありがとうございます。

**Comment by yuru7** [comment]
検証のご協力、本当にありがとうございました🙇‍♂️
修正を適用した v0.0.5 をリリースしたので、クローズします。
