### ISSUE TITLE
Windows TerminalにおいてNerd Fontの表示が崩れる

### ISSUE THREAD

**Issue by maemon4095** [yuru7/moralerspace#3]
Windows TerminalにおいてNerd Fontの表示が崩れます．

![brokennerd](https://github.com/yuru7/moralerspace/assets/47819358/89526d0f-e76c-4d10-ab6d-5220177c6e35)
(Moralerspace v0.0.6, HackGen v2.9.0, Windows Terminal v1.18.10301.0, Alacritty v0.13.1)
HWNF版でも同様に表示が崩れますが，HackGenでは表示は崩れません．

表示を見た限りでは，行の高さよりNerd Fontの高さが低いことが原因の様に見えます．

Alacritty及びVSCodeにおいては表示が崩れないため，Windows Terminal側の問題の可能性もあるかと思いますが，
自分ではどちらの問題か判別できなかったため，確認していただければと思います．

**Comment by yuru7** [comment]
ご報告ありがとうございます！
Windows Terminalでずれることを再現できました。
また、たしかにVSCode内蔵のターミナルで見るとずれないようです。描画方式になんらか違いがあるのでしょうが、詳細は不明です。

Nerd Fontsが公式に配布しているフォントと見比べてみて、おおよそ原因が掴めた気がします。

原因の被疑:

1. Powerline用グリフの高さが、本フォントで設定する高さより低い状態だったこと
2. フォントの高さ、深さを決める設定値が、Nerd Fontsで指定している具合と異なったこと (EM高よりもtypeascent + typedescentの方が高く設定されている) 

上記について調整して試しにビルドしたものを以下に配置しました。よろしければ検証のご協力をお願いいたします🙇‍♂️
https://github.com/yuru7/moralerspace/tree/issue3/test_build

**Comment by maemon4095** [comment]
対応ありがとうございます．
\uE0B0(三角形)は正常に表示できていることが確認できました．
![triangle](https://github.com/yuru7/moralerspace/assets/47819358/f5785968-3dd9-4b88-a7c9-94f928e3c68d)

ですが，Box-drawing characterの表示がおかしいようです．
![boxdrawingchar_moraler](https://github.com/yuru7/moralerspace/assets/47819358/4de2adde-861c-45e2-950c-c5eaaa8cafe5)

HackGenでは以下の様に表示されるものです．
![boxdrawingchar_hackgen](https://github.com/yuru7/moralerspace/assets/47819358/3f213044-5cf6-4d34-8447-72621f3aae2a)

また，当初と同様にAlacrittyやVSCodeのTerminalにおいては正常に表示されます．
![boxdrawingchar_moraler_alacritty](https://github.com/yuru7/moralerspace/assets/47819358/b51ee29d-ebe1-4234-922b-1041b26a2158)

加えて，Box-drawing characterは文字幅がおかしいようにも見えます．
![sl_moraler](https://github.com/yuru7/moralerspace/assets/47819358/7a0f2a6f-1120-4454-80e4-447334386038)
![sl](https://github.com/yuru7/moralerspace/assets/47819358/cf3c12c3-571f-4074-b9cb-ab1c2b5acf73)

VSCodeのエディタにおいてもずれて表示されます
![vscode](https://github.com/yuru7/moralerspace/assets/47819358/213d1447-cb13-4c71-be18-dfa9879cdd6f)

以下に上記で試した際に表示の崩れた文字列を挙げておきます．
```text
╭────┬─────────────────────────┬─────────┬─────────┬─────────────╮
│  # │          name           │  type   │  size   │  modified   │
├────┼─────────────────────────┼─────────┼─────────┼─────────────┤
│  0 │ .aws                    │ dir     │     0 B │ 6 days ago  │
│  1 │ .azure                  │ dir     │     0 B │ 6 days ago  │
│  2 │ .bash_history           │ file    │    55 B │ 5 days ago  │
│  3 │ .cache                  │ dir     │     0 B │ 6 days ago  │
```

```text
  × External command failed
   ╭─[entry #1:1:1]
 1 │ sl
   · ─┬
   ·  ╰── executable was not found
   ╰────
  help: program not found
```

**Comment by yuru7** [comment]
確認ありがとうございます。
確認したところBox Drawingについては、合成の仕組み上の不良というよりMonaspaceに該当グリフが含まれていないことによるものですね。そのため、どのバリエーションにおいてもIBM Plex Sans JPの罫線が合成され表示されるようです。

Nerd Fonts合成周りとは異なる事象のため、対処するとしたら別の方法 (罫線グリフだけ別フォントから持ってきて合成するとか) をとる必要があるため、別のissueとして取り扱わせてください。

Monaspaceの U+2500 周辺:

![image](https://github.com/yuru7/moralerspace/assets/13458509/ef994915-296c-4b4a-a542-7527f69a8501)

**Comment by maemon4095** [comment]
対応ありがとうございます．
Box-drawing characterはそもそもグリフに含まれていないんですね．幅の不具合かと思っていました．
もし可能であれば含まれていると嬉しいです．

Nerd Fontに関して，Font Awesomeのアイコンの幅が狭い（おそらく全角でないといけない？）ように見えます．
![fontawesome](https://github.com/yuru7/moralerspace/assets/47819358/8e49e562-532b-4993-8c12-d4b834ddb719)

粗探しのようで申し訳ないですが，確認お願いします。

**Comment by yuru7** [comment]
> Nerd Fontに関して，Font Awesomeのアイコンの幅が狭い（おそらく全角でないといけない？）ように見えます．

結論からいうと、これは仕様通りです。
Font Awesomeのようなアイコングリフの描画領域に対して、幅設定の方が狭く設定されているためです。これは、Nerd Fonts公式配布フォントでいうところの標準版と同等の仕様です。

Nerd Fontsの公式配布版フォントですが、それぞれに3種のバリエーションがあります。

- 標準版: 各グリフの幅はASCIIグリフと同等。Font Awesomeのようなアイコングリフは、その幅を超えて表現される。 (下図 1)
- モノスペース版: 各グリフの幅はASCIIグリフと同等。Font Awesomeのようなアイコングリフは、その幅に揃えて表現される。 (下図 2)
- プロポーショナル版: 各グリフの幅はプロポーショナルで、Font Awesomeのようなアイコングリフの幅に揃えて設定される。 (下図 3)

上記で「幅」と表現しているのは、下図で赤丸で囲んでいる箇所の値です。この値に沿って各エディタ等のソフトウェアでは、1文字の表示幅を決定します。

一方で標準版 (下図 1) のように、設定された幅よりも大きく描画されているグリフについては隣接の文字にめり込むような表示となってしまいます。これを回避するには、隣接に半角スペースを置くなどして右隣に隙間を作ればいいわけです。このアプローチをとっているツールは比較的多いような気がします。

そして、このめり込みを防ぐには一律モノスペース版を使えばいいという話になりますが、そうすると縦横比を維持したままASCIIグリフと同じ幅に狭めるわけなので、Font Awesomeのようなアイコングリフはだいぶ小さくなります。 (下図 2 で、下図 1, 3 よりグリフ高が低くなっているのが見て取れる)

では幅をグリフと同じにしたプロポーショナル版がよいか、と言うと、今度はターミナルアプリによってはプロポーショナルフォントはうまく扱えなかったりすることがあります。

結局はアプリやツールとの相性問題によって、「標準版を使ってみる → モノスペース版 or プロポーショナル版 を使う」という順序で利用するバリエーションを選択することになります。

上記の全バリエーションを用意することもできなくはないですが、あまりにバリエーションが膨れ上がってしまいビルドに膨大な時間がかかってしまうため、標準版に揃えたもののみを用意するというところを落とし所にしています。

---

図 1 標準版:

![image](https://github.com/yuru7/moralerspace/assets/13458509/e981ae76-bbac-4a37-a733-0933394fc1f0)

図 2 モノスペース版:

![image](https://github.com/yuru7/moralerspace/assets/13458509/072ae175-2dd9-45df-a34c-e90412c1c000)

図 3 プロポーショナル版:

![image](https://github.com/yuru7/moralerspace/assets/13458509/ae3cfb31-4438-42c7-861b-c9145434982c)

**Comment by yuru7** [comment]
罫線素片、Powerline の位置調整に対処した v0.0.7 をリリースしましたので、お暇なときにお試しください✋

**Comment by maemon4095** [comment]
対応いただきありがとうございます。罫線素片があるとTerminalで利用できるので大変うれしいです．

Nerd Fontに関しまして，Font Awesomeにの幅が仕様である旨承知しました．
他のグリフに関しては自分が利用した限りでは表示に問題ないように見えます．

ありがとうございました．
