### ISSUE TITLE
macOSでJPDOCのKripton,Radonがpostテーブルの使用性エラーになる

### ISSUE THREAD

**Issue by berlysia** [yuru7/moralerspace#4]
v0.0.8 のJPDOC版をインストールする際に、Kripton, Radonだけで表題のように失敗しました。
JPDOC版のみ遡ってためしてみましたところ、v0.0.6から発生するようでした。

**Comment by berlysia** [comment]
@yuru7 リンク先からダウンロードしたファイルでは、すべて無事にインストールができました！

**Comment by yuru7** [comment]
ご確認ありがとうございます 🙇‍♂️
対処を行った v0.0.9 をリリースしました。
