### ISSUE TITLE
udev-gothic等とフォントの高さが違いますが、仕様でしょうか？

### ISSUE THREAD

**Issue by yamam** [yuru7/moralerspace#5]
フォントサイズ11でのメモ帳で全画面表示したときの表示行数がHackGen, udev-gothic, PlemolJPと異なっていますが、仕様でしょうか？
これらのフォントから乗り換えることが多いと思いますので、高さが同じ方が乗り換えのハードルが下がるかと思います。

HackGen, udev-gothic, PlemolJP
54行

moralerspace
51行

**Comment by yuru7** [comment]
だいぶ長らく見逃していました。申し訳ないです。

特に公開する他フォントと高さを揃えようとする意図はありませんので、仕様といえばその通りです。

合成に使わせていただいている字体の雰囲気など、その時々で行間の高さは見やすいように調整しているので、今後変更することがあるかもしれませんし、現状のままかもしれません。

**Comment by yamam** [comment]
ご回答ありがとうございました
