### ISSUE TITLE
(v1.0.0) Argon JPDOC でだけリガチャが効かないです

### ISSUE THREAD

**Issue by shuntaroy** [yuru7/moralerspace#6]
素晴らしいフォントをありがとうございます！

V1.0.0から，JPDOCの他のバージョンではリガチャが効くようなのですが，Argonでだけ効かないようです．
VSCodeで下記の設定です．

```json
  "editor.fontLigatures": "'ss01', 'ss02', 'ss03', 'ss04', 'ss05', 'ss06', 'ss07', 'ss08', 'calt', 'dlig'",
```

**Comment by yuru7** [comment]
ご報告ありがとうございます。

Moralerspace Argon JPDOC で試してみましたが、こちらの環境では特に問題なさそうでした。

Moralerspaceを以前のバージョンからご利用で、かつWindowsの場合、もしかすると下記の上書きインストール問題があるかもしれません。こちらを参考に再インストールを試してみるとよいかもしれません。
https://github.com/yuru7/HackGen/issues/20#issuecomment-735329565

確認環境:

- OS: Windows 11 23H2
- VSCode: 1.88.0

設定:

```json
    "editor.fontFamily": "Moralerspace Argon JPDOC",
    "editor.fontLigatures": "'ss01', 'ss02', 'ss03', 'ss04', 'ss05', 'ss06', 'ss07', 'ss08', 'calt', 'dlig'",
```

表示させたテキスト:

```
<>a|->b++c->
<!--d~~>e->>
/==f<=g###h|>
```

表示結果:

![image](https://github.com/yuru7/moralerspace/assets/13458509/17c3dade-87ed-4c1a-85a8-e45261e6805b)

**Comment by shuntaroy** [comment]
早速のご返信ありがとうございます．
時間を置いてVScodeを開きなおしたところ，Argon JPDOCでもリガチャが効いていました．
当初，エディタの再起動等で直らなかったのでissueを立ててしまいまして，失礼いたしました．
環境はMacなのですが，上書きインストールをしていました．
ご紹介いただいたWindowsの事例と同様かわかりませんが，たまたまOSで何かのキャッシュが効いてしまっていたかもしれないですね．
解決しましたのでissue閉じさせていただきます．お騒がせしてすみません．
