### ISSUE TITLE
全角スペースの幅が若干狭い

### ISSUE THREAD

**Issue by moscoc** [yuru7/moralerspace#7]
全角スペースの幅が、その他の全角文字より若干狭くなっているようです。

> <img width="332" alt="image" src="https://github.com/yuru7/moralerspace/assets/172269458/4593232c-f57c-4331-980f-135af9de5dbb">

表示確認をした VSCode の設定は下記のとおりです。

```jsonc
// .vscode/settings.json
{
    "editor.fontSize": 13,
    "editor.fontWeight": 400,
    "editor.fontFamily": "'Moralerspace Argon HWJPDOC', monospace",
    "editor.lineHeight": 1.25,
    "editor.fontLigatures": true
}
```

**Comment by yuru7** [comment]
ご報告ありがとうございます！
v1.0.2 で対処しました。お試しください。
https://github.com/yuru7/moralerspace/releases/tag/v1.0.2

**Comment by moscoc** [comment]
@yuru7 
修正が確認できました。
迅速なご対応、ありがとうございました 🙇‍♂️
